# Polychrome::createPalette(30, seedcolors = c("#000000", "#FF0000", "#00FF00", "#0000FF"))


color.palette <- c(
  "red",
  "blue",
  "tan1",
  "green",
  "azure3",
  "deeppink",
  "magenta",
  "darkviolet",
  "tan",
  "aquamarine",
  "black",
  "maroon",
  "cadetblue",
  "peru",
  "lightpink",
  "plum4",
  "blue4",
  "gold3",
  "mediumpurple1",
  "khaki1",
  "firebrick3",
  "dodgerblue",
  "forestgreen",
  "indianred1",
  "darkorange",
  "dimgrey",
  "antiquewhite",
  "coral",
  "moccasin",
  "lightseagreen",
  "darkturquoise",
  "darkgreen",
  "darkolivegreen2",
  "lightcoral",
  "khaki4",
  "darkorchid1",
  "plum",
  "cadetblue1",
  "darksalmon",
  "lightsalmon",
  "darkslategray",
  "salmon4",
  "brown",
  "goldenrod1",
  "slategray2",
  "black"
)
color.palette <- c(color.palette, color.palette, color.palette)

default.named.palette <- c(
	"0"	=	 "#F60D16",
	"1"	=	 "#001CFF",
	"2"	=	 "#00F90D",
	"3"	=	 "#9FBED7",
	"4"	=	 "#FC00D5",
	"5"	=	 "#730DB6",
	"6"	=	 "#9B6D00",
	"7"	=	 "cadetblue1",
	"8"	=	 "#FDDB0D",
	"9"	=	 "#FA8986",
	"10"	=	"#D5A7FF",
	"11"	=	"black",
	"12"	=	"#A2DE94",
	"13"	=	"#D02EFF",
	"14"	=	"#00B1FB",
	"15"	=	"#951671",
	"16"	=	"#FEDACE",
	"17"	=	"#C0F416",
	"18"	=	"#2A4586",
	"19"	=	"#F96900",
	"20"	=	"#0D9880",
	"21"	=	"#00F899",
	"22"	=	"#FEA8D8",
	"23"	=	"#536800",
	"24"	=	"#FDA338",
	"25"	=	"#9F0016",
	"26"	=	"#C038C2",
	"27"	=	"#955155",
	"28"	=	"#F60D89",
	"29"	=	"darkgreen",
	"30"	=	"cadetblue",
	"31"	=	"darksalmon",
	"32"	=	"darkorchid1",
	"33"	=	"dodgerblue",
	"34"	=	"mediumpurple1",
	"35"	=	"azure3",
	"36"	=	"khaki1"
)

adip.cols <- c(
	"mast_cell"      = "red", 
	"adipocyte"      = "orange", 
	"ASPC"           = "green", 
	"endothelial"    = "blue", 
	"SMC"            = "lightcoral", 
	"LEC"            = "dodgerblue", 
	"macrophage"     = "darkviolet", 
	"mesothelium"    = "tan", 
	"dendritic_cell" = "aquamarine", 
	"endometrium"    = "black", 
	"t_cell"         = "maroon", 
	"monocyte"       = "cadetblue", 
	"b_cell"         = "khaki4", 
	"pericyte"       = "mediumpurple1", 
	"Unassigned"     = "gray"
)
